<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UseWindowsForms>false</UseWindowsForms>
    <IsTestProject>true</IsTestProject>
    <DefineConstants>$(DefineConstants);UNIT_TEST</DefineConstants>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" />
    <PackageReference Include="Avalonia.Headless.NUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../src/app/GitExtensions.Avalonia/GitExtensions.Avalonia.csproj" />
  </ItemGroup>
</Project>